import type { Metadata } from "next";
import { notFound } from "next/navigation";
import BusinessCard from "@/components/business-card";
import { SITE } from "@/lib/site";
import { isLocale, OG_LOCALE, LOCALES, localizedHref, type Locale } from "@/lib/i18n";

// The digital business card. Public slugs: /card (en), /de/visitenkarte, /it/biglietto — the
// mapping lives in SLUG_TRANSLATIONS in lib/i18n.ts and is applied by proxy.ts.
//
// The QR in public/qr-biglietto.svg points at the UNPREFIXED /card, so a phone that scans it
// gets the card in its own language: proxy.ts negotiates Accept-Language and sends a German
// handset to /de/visitenkarte without Francesco having to pick a link.

const META: Record<Locale, { title: string; description: string }> = {
  de: {
    title: "Visitenkarte · Francesco Modolo · Modolo Digital Studio",
    description:
      "Die Visitenkarte von Francesco Modolo, Modolo Digital Studio in Winterthur: Kontakt speichern oder direkt auf WhatsApp schreiben. Ich antworte selber.",
  },
  it: {
    title: "Francesco Modolo · Siti web e Google, Winterthur",
    description:
      "Il mio biglietto da visita: salvi il contatto o mi scriva su WhatsApp. Siti web, scheda Google, foto e video. Il prezzo lo decidiamo prima.",
  },
  en: {
    title: "Francesco Modolo — Modolo Digital Studio, Winterthur",
    description:
      "The business card of Francesco Modolo, Modolo Digital Studio in Winterthur. Save my contact, message me on WhatsApp or send an email — I answer myself.",
  },
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ lang: string }>;
}): Promise<Metadata> {
  const { lang } = await params;
  if (!isLocale(lang)) return {};
  const m = META[lang];

  // The preview image is the FRONT of the printed card (generated by
  // scripts/biglietto-digitale.mjs). It is the whole reason to send a link rather than a photo:
  // in a WhatsApp thread the recipient sees a business card before deciding whether to tap.
  const og = `/og-biglietto-${lang}.png`;

  return {
    // `absolute`, not a bare string: the [lang] layout sets a "%s | Modolo Digital Studio"
    // template, and every one of these titles already ends with the studio name — a plain string
    // would render it twice in the tab and in the WhatsApp link preview.
    title: { absolute: m.title },
    description: m.description,
    // noindex, follow: it is a near-duplicate of the homepage's contact details and would
    // compete with the page that is actually meant to rank. Kept out of app/sitemap.ts too.
    robots: { index: false, follow: true },
    alternates: {
      canonical: localizedHref(lang, "/biglietto"),
      languages: Object.fromEntries(LOCALES.map((l) => [l, localizedHref(l, "/biglietto")])),
    },
    openGraph: {
      type: "profile",
      locale: OG_LOCALE[lang],
      url: localizedHref(lang, "/biglietto"),
      siteName: SITE.name,
      title: m.title,
      description: m.description,
      images: [{ url: og, width: 1200, height: 630, alt: `${SITE.founder} — ${SITE.name}` }],
    },
    twitter: { card: "summary_large_image", title: m.title, description: m.description, images: [og] },
  };
}

export default async function Page({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params;
  if (!isLocale(lang)) notFound();
  return <BusinessCard lang={lang} />;
}
